### PR TITLE
Front end profiles

### PR DESCRIPTION
**Pull request by mrlarso**
- [x] Create public/private profile view on FrontEnd

- [x] Update Ember user model for profile fields

- [x] Update Server user model

- [x] Allow profile fields to be updated

- [ ] Server authorization for updating user model

- [ ] Write tests

### CODE REVIEW

**Comment by Jakeii** [comment]
Sweet, need a link to the profile somewhere though?

**Comment by mrlarso** [comment]
Theres one included in Kiki's navigation bar, should there be another one
somewhere?

**Comment by Jakeii** [comment]
Is that in a different branch?

**Comment by mrlarso** [comment]
Yeah, in master branch now after the Frontend-MVP pull request

**Pull request merged**
