### PR TITLE
[bug fix] see description for a list of bug fixes

### LINKED ISSUE #186: [BUG] [BACKEND] Generating Slugs
### Describe the bug:
Slugs should be generated by the back-end
Slugs should not be editable

### Expected Behavior
Slugs should be created by back-end
Once a course/module.less--- etc is published, user should not be able to edit the slug as this might make previously shared links invalid

### Current Behavior
Slug is  currently generated by front-end
Editing an entity edits the slug too

### LINKED ISSUE #253: [BUG] Migration Fail on new instance
### Describe the bug:

Recent changes to migrations make them fail on new instances

dropping the column fails because the column doesn't exist on new instance
```

        .table('table name', table => {
      table.dropColumn('column name');

    });
```

### Expected Behavior

Migrations should not fail
Migrations should check if column exists before dropping

### Current Behavior

`migration failed with error: alter table "table name" drop column "column name" - column "column name" of relation "table name" does not exist`

### Steps to reproduce
run migration on new instance of wikonnect

### LINKED ISSUE #256: [FEATURE] [BACKEND] Validate token endpoint
### Describe the user story:

3rg party should be able to validate auth token

### LINKED ISSUE #266: [BUG] Descriptive error messages in dev environment
### Tell us about your browser and operating system:
- Operating System:
- NodeJS Version:
- Ember Version:

### Screenshots where applicable

### LINKED ISSUE #267: [BUG] saving h5p chapter shouldn't require lesson ID
### Tell us about your browser and operating system:
- Operating System:
- NodeJS Version:
- Ember Version:

### Screenshots where applicable

### LINKED ISSUE #269: [BUG] public chapters api should only show published content
### Tell us about your browser and operating system:
- Operating System:
- NodeJS Version:
- Ember Version:

### Screenshots where applicable

### PR DESCRIPTION
**Pull request by mosesokemwa**
- [x] I have read [Wikonnect contributing guidelines](https://github.com/tunapanda/wikonnect/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request passes all test.

Closes #269
Closes #267 
Closes #253 
Closes #256 
Closes #186 
Closes #266 

#### Change Log
1. Saving chapters does not require the lesson ID
2. Chapters public API returns published content only, this creates a problem in fetching all the draft and archived content[to be fixed at a later date by me, **UPDATE** this is fixed]
3. Fixed missing migrations file was screwing with database schema
4. All slugs are autogenerated in the backend and are not the front end
5. Getting current user is now simplified by replacing the ``/:id`` field with keyword ``current`` in the user routes

```
http://localhost:3000/api/v1/users/:id
http://localhost:3000/api/v1/users/current
```
6. Dev environment produces a more descriptive error why building[Kiki should be smiling]

### CODE REVIEW

**Comment by proverbial-ninja** [comment]
Ideally if I am authenticated I should see my own drafts

**Comment by proverbial-ninja** [comment]
don't merge ... this will break teachers platform

**Comment by mosesokemwa** [comment]
@proverbial-ninja whats the expected outcomes from that route.
1. Authenticated user should.....
2. Anonymous user should.....

**Comment by proverbial-ninja** [comment]
Authenticated user should see all the chapters they've created

Both Authed and anonymous user should only see the published chapters form ```/chapters ``` endpoint

**Comment by mosesokemwa** [comment]
@proverbial-ninja I need you to review the bug fix for published and draft chapters concerning authenticated and anonymous users

See change log for a list

**Pull request merged**
