### PR TITLE
Elasticsearch

### LINKED ISSUE #9: Configure ElasticSearch index and queries
As a user, I would like to be able to search everything.
As a frontend engineer, I would like to be able to search everything via the API.

- [x] Configure ElasticSearch index
- [x] Use queries to create an API endpoint for search
- [ ] Test the search API endpoint
- [x] Design search queries
- [x] Index things when they are inserted into the database
- [x] Update the index when things are updated

### PR DESCRIPTION
**Pull request by Jakeii**
Closes #9

### CODE REVIEW

**Comment by mrlarso** [comment]
@Jakeii  what's the correct procedure for indexing/reindexing?

**Comment by Jakeii** [comment]
run `node bin/reindex-search.js` should index your database into elasticsearch

**Comment by mrlarso** [comment]
Hmm that's what I've been trying, but I'm getting the bellow error:

`node reindex-search.js 
indexing learning_paths...
indexing courses...
indexing modules...
indexing lessons...
indexing chapters...
Connected to Elasticsearch index swag-v1-undefined on http://localhost:9200 successfully
{ ResponseError: mapper_parsing_exception
    at IncomingMessage.response.on (/home/mick/coding/tunapanda/swag/server/node_modules/@elastic/elasticsearch/lib/Transport.js:287:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'ResponseError',
  meta: 
   { body: { error: [Object], status: 400 },
     statusCode: 400,
     headers: 
      { 'content-type': 'application/json; charset=UTF-8',
        'content-length': '233' },
     warnings: null,
     meta: 
      { context: null,
        request: [Object],
        name: 'elasticsearch-js',
        connection: [Object],
        attempts: 0,
        aborted: false } } }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '3443cebe-e774-4fb9-86e6-6e5e9a941499',
  sql: 'select 1' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '5a600598-22b8-467f-864d-79fcd4819887',
  sql: 'select "learning_paths".* from "learning_paths"' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'f78960f8-a436-45b9-99d5-ce40edcaf533',
  sql: 'select "courses".* from "courses"' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '4e6b7103-8844-4875-9e8b-8aa81e6f850b',
  sql: 'select "modules".* from "modules"' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '3a529f95-4ccb-4043-93b1-85199610561e',
  sql: 'select "lessons".* from "lessons"' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'adafc704-9f56-48e4-80a1-f9389aae6eb4',
  sql: 'select "chapters".* from "chapters"' }
Connected to db swag@localhost:undefined as tunapanda successfully
`

Not sure if I missed something when configuring, but I'm able to run query elastic search it's just the indexing that appears not to work.

**Comment by Jakeii** [comment]
hmm try `export NODE_ENV=development; node bin/reindex-search.js`

**Comment by mrlarso** [comment]
Sweet, that solved the indexing issue

**Pull request merged**
